Make git hf feature pull more verbose (to match existing commands), and fix broken error handling

diff --git a/git-hf-feature b/git-hf-feature
--- a/git-hf-feature
+++ b/git-hf-feature
@@ -610,20 +610,20 @@ cmd_pull() {
 		# we already have a local branch called like this, so simply pull the
 		# remote changes in
 		if flag rebase; then
-			if ! git pull --rebase -q "$REMOTE" "$BRANCH"; then
+			if ! git pull --rebase "$REMOTE" "$BRANCH"; then
 				warn "Pull was aborted. There might be conflicts during rebase or '$REMOTE' might be inaccessible."
 				exit 1
 			fi
 		else
-			git pull -q "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
+			git pull "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
 		fi
 
 		echo "Pulled $REMOTE's changes into $BRANCH."
 	else
 		# setup the local branch clone for the first time
-		git fetch -q "$REMOTE" "$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
+		git fetch "$REMOTE" "$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
 		git branch --no-track "$BRANCH" FETCH_HEAD || die "Branch failed."
-		git checkout -q "$BRANCH" || die "Checking out new local branch failed."
+		git checkout "$BRANCH" || die "Checking out new local branch failed."
 		echo "Created local branch $BRANCH based on $REMOTE's $BRANCH."
 	fi
 }
@@ -657,7 +657,7 @@ cmd_push() {
 		echo "- The local branch '$BRANCH' was configured to track the remote branch"
 		echo
 	else
-		git push "$REMOTE" "$BRANCH:refs/heads/$BRANCH" || due "Push failed"
+		git push "$REMOTE" "$BRANCH:refs/heads/$BRANCH" || die "Push failed"
 
 		echo
 		echo "Summary of actions:"
