Add "feature submit" to submit a Pull Request
Instead of merging and pushing features directly yourself, we want to
use GitHub's powerful Pull Requests to mandate independent code-review.

A new command is added to automate submission of a feature as a Pull
Request:

    git flow feature submit [<name>]

The name of the feature branch to submit is optional, with the current
feature branch (if you're on one) as the default.

A number of utility functions are also added to facilitate working with
the GitHub API:

  * `github_post` - posts an authenticated request to GitHub's API.
  * `github_auth_token` - gets the API OAuth2 token for GitHub. If no
    token exists for the repo, the user will be prompted for
    credentials required to create one and a token will be generated.
  * `github_origin_repo` - extracts the GitHub name of the remote
    origin (if it's a GitHub origin) in the format: <user>/<repo>

The full submission process should have the following outcomes:

  * The feature branch is pushed to `origin`
  * The first time a user requires authentication for a repo, they
    will be prompted for a username and password.
  * The default editor will be opened for the user to enter a
    summary of the feature they're submitting.
  * A new Pull Request is created from the feature branch to `develop`

Outstanding work includes:

  * Infer the feature description from the commit message when the
    feature contains only a single (non-merge) commit.
  * Infer the feature description from the history of the feature and
    feature name when the feature involves many commits.

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -1,3 +1,4 @@
+#!/bin/env bash
 #
 # git-flow -- A collection of Git extensions to provide high-level
 # repository operations for Vincent Driessen's branching model.
@@ -44,6 +45,7 @@ PREFIX=$(git config --get gitflow.prefix.feature)
 usage() {
 	echo "usage: git flow feature [list] [-v]"
 	echo "       git flow feature start [-F] <name> [<base>]"
+	echo "       git flow feature submit [<name>] [<base>]"
 	echo "       git flow feature finish [-rFkD] [<name|nameprefix>]"
 	echo "       git flow feature publish <name>"
 	echo "       git flow feature track <name>"
@@ -223,6 +225,80 @@ cmd_start() {
 	echo "- You are now on branch '$BRANCH'"
 	echo ""
 	echo "Now, start committing on your feature. When done, use:"
+	echo ""
+	echo "     git flow feature finish $NAME"
+	echo
+}
+
+cmd_submit() {
+	parse_args "$@"
+        BASE=${2:-$DEVELOP_BRANCH}
+	name_or_current
+
+	require_branch "$BRANCH"
+
+        require_github_origin_repo
+
+	# push to origin
+	if ! git push "$ORIGIN" "$BRANCH"; then
+		die "Failed to push '$BRANCH' to '$ORIGIN'"
+	fi
+
+	# pull request details
+	PR_FILE="./COMMIT_MSG"
+	PR_TITLE=
+	PR_DESC=
+
+	rm -f $PR_FILE
+
+	# ask the user for a pull request description
+	editor $PR_FILE
+
+	# extract pull request parameters from description
+	if [ -r PR_FILE ]; then
+		PR_TITLE=`head -n1 $PR_FILE | sed -e 's/^[[:space:]]*//'`
+		PR_DESC=`tail -n+2 $PR_FILE | sed -e 's/^[[:space:]]*//'`
+	fi
+
+	# ensure there's an adequate description
+	if [ -z PR_TITLE ]; then
+		warn "Aborting submission due to empty description."
+		warn ""
+		warn "To submit a feature, use:"
+		warn ""
+		warn "     git flow feature submit [<name>]"
+		warn ""
+		warn "Enter a description for the feature when prompted, in the"
+		warn "format of a Git commit:"
+		warn ""
+		warn "     Short feature summary, no longer than 72 chars"
+		warn ""
+		warn "     A longer description of the feature, including a summary"
+		warn "     of backwards incompatible changes, wrapped at 80 chars."
+		warn 
+		exit 1
+	elif [ -z PR_DESC ]; then
+		warn "Empty feature long description."
+		warn "In future, you should enter both a summary and detailed description"
+		warn "when submitting a feature."
+	fi
+
+	# submit pull request to GitHub and parse Pull Request URL from response
+        PR_URL=`sed -rn 's/.+"html_url":\s*"(.+\/pulls\/.+)".+/\1/p' <<< \
+          $(github_post \
+            "/repos/$GITHUB_ORIGIN/pulls" \
+            "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_DESC\",\"head\":\"$BRANCH\",\"base\":\"$BASE\"}")`
+
+	if [ -z $PR_URL ]; then
+		die "Failed to create Pull Request"
+	fi
+
+	echo
+	echo "Summary of actions:"
+	echo "- The branch '$BRANCH' was pushed to '$ORIGIN'"
+	echo "- A Pull Request from '$BRANCH' to '$BASE' was created at '$PR_URL'"
+	echo ""
+	echo "Once the Pull Request has been accepted, cleanup the feature with:"
 	echo ""
 	echo "     git flow feature finish $NAME"
 	echo
diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -1,3 +1,4 @@
+#!/bin/env bash
 #
 # git-flow -- A collection of Git extensions to provide high-level
 # repository operations for Vincent Driessen's branching model.
@@ -238,6 +239,75 @@ gitflow_resolve_nameprefix() {
 			return 2
 		fi
 	fi
+}
+
+#
+# GitHub speicific common functionality
+#
+GITHUB_API_URL="https://api.github.com"
+GITHUB_AUTH_TOKEN_KEY="github.oauth.token"
+
+#
+# Gets the GitHub OAuth token for this user/repo
+# If no token has been created, the user will be prompted to create one.
+#
+github_auth_token() {
+  GITHUB_TOKEN=`git config --get "$GITHUB_AUTH_TOKEN_KEY"`
+
+  if [ -z $GITHUB_TOKEN ]; then
+    read -p "GitHub Username: " USER
+    read -s -p "GitHub Password: " PASS
+
+    if [ -z USER ]; then
+      die "You must enter your GitHub username to authenticate with"
+    fi
+
+    if [ -z PASS ]; then
+      die "You must enter your GitHub password to authenticate with"
+    fi
+
+    GITHUB_TOKEN = `curl -s \
+      -u "$USER:$PASS" \
+      -d '{"scopes":["repo"],"note":"gitflow automation"}' \
+      "$GITHUB_API_URL/authorizations" | 
+    sed -rn 's/.+"token":\s*"(.+)".+/\1/p'`
+
+    git config "$GITHUB_AUTH_TOKEN_KEY" "$GITHUB_TOKEN"
+  fi
+}
+
+# Ensures we have been authorized on GitHub
+require_github_auth_token() {
+  github_auth_token
+
+  if [ -z $GITHUB_TOKEN ]; then
+    die "Failed to authorize GitHub user '$USER' for '$ORIGIN'"
+  fi
+}
+
+# Gets the name of the origin repo on GitHub
+# e.g. datasift/gitflow
+github_origin_repo() {
+  GITHUB_ORIGIN=`sed -rn 's/.+[:\/](.+\/.+)\.git/\1/p' <<< "$ORIGIN"`
+}
+
+require_github_origin_repo() {
+  github_origin_repo
+
+  if [ -z $GITHUB_ORIGIN ]; then
+    die "The default remote repo, '$ORIGIN' is not a GitHub repository."
+  fi
+}
+
+# Posts an authenticated request to GitHub and returns the response
+github_post() {
+  require_github_auth_token
+
+  resp=`curl -s -H "Authorization: bearer $GITHUB_TOKEN" -d $2 $1`
+
+  if [ $? -eq 0 ]; then
+    echo $resp
+  fi
 }
 
 #
