New: rename commands (beta)

diff --git a/git-hf-feature b/git-hf-feature
--- a/git-hf-feature
+++ b/git-hf-feature
@@ -57,6 +57,7 @@ usage() {
 	echo "       git hf feature pull [-r] [<remote> [<name>]]"
 	echo "       git hf feature push [<remote> [<name>]]"
 	echo "       git hf feature cancel [-f] <name>"
+	echo "       git hf feature rename <new-name>"
 }
 
 cmd_default() {
@@ -134,6 +135,14 @@ cmd_help() {
 require_name_arg() {
 	if [ "$NAME" = "" ]; then
 		warn "Missing argument <name>"
+		usage
+		exit 1
+	fi
+}
+
+require_newname_arg() {
+	if [[ -z $NAME ]] ; then
+		warn "Missing argument <new-name>"
 		usage
 		exit 1
 	fi
@@ -585,5 +594,47 @@ cmd_cancel() {
 	else
 		echo "- Feature branch '$FEATURE_BRANCH' has been deleted locally"
 	fi
+	echo
+}
+
+cmd_rename() {
+	# sort out our args
+	parse_args "$@"
+	require_newname_arg
+	NEWNAME=$NAME
+	use_current_feature_branch_name
+
+	# make sure the new branch has the feature prefix
+	if ! echo "$NEWNAME" | grep -q "^$FEATURE_PREFIX" ; then
+		NEWNAME="$FEATURE_PREFIX$NEWNAME"
+	fi
+
+	# we need to know the current state of $ORIGIN
+	hubflow_fetch_latest_changes_from_origin
+
+	# sanity checks
+	require_branch "$FEATURE_BRANCH"
+	require_branch_absent "$NEWNAME"
+	require_branch_absent "$ORIGIN/$NEWNAME"
+
+	# keep track of what we did
+	local removed_remote=0
+
+	# do it
+	git branch -m "$FEATURE_BRANCH" "$NEWNAME" || die "could not rename local branch"
+	if git_branch_exists "$ORIGIN/$FEATURE_BRANCH" ; then
+		git push $ORIGIN ":$FEATURE_BRANCH" || die "could not delete remote branch '$FEATURE_BRANCH' at $ORIGIN"
+		removed_remote=1
+	fi
+	git push "$ORIGIN" "$NEWNAME" || die "could not push new branch '$NEWNAME' to $ORIGIN"
+
+	# summary
+	echo
+	echo "Summary of actions:"
+	echo "- The local branch '$FEATURE_BRANCH' has been renamed to '$NEWNAME'."
+	if [[ $removed_remote == 1 ]] ; then
+		echo "- The remote branch '$FEATURE_BRANCH' at $ORIGIN was removed."
+	fi
+	echo "- The local branch '$NEWNAME' has been pushed to $ORIGIN."
 	echo
 }
diff --git a/git-hf-hotfix b/git-hf-hotfix
--- a/git-hf-hotfix
+++ b/git-hf-hotfix
@@ -53,6 +53,7 @@ usage() {
 	echo "       git hf hotfix pull [-r] [<remote> [<version>]]"
 	echo "       git hf hotfix push [<remote> [<version>]]"
 	echo "       git hf hotfix cancel [-f] <version>"
+	echo "       git hf hotfix rename <new-version>"
 }
 
 cmd_default() {
@@ -155,6 +156,14 @@ parse_remote_name() {
 require_version_arg() {
 	if [ "$VERSION" == "" ]; then
 		warn "Missing argument <version>"
+		usage
+		exit 1
+	fi
+}
+
+require_newversion_arg() {
+	if [[ -z $VERSION ]] ; then
+		warn "Missing argument <new-version>"
 		usage
 		exit 1
 	fi
@@ -521,4 +530,47 @@ cmd_pull() {
 
 cmd_push() {
 	git hf push "$@"
+}
+
+cmd_rename() {
+	# sort out our args
+	parse_args "$@"
+	require_newversion_arg
+	NEWNAME=$VERSION
+	use_current_hotfix_branch_name
+
+	# make sure the new branch has the hotfix prefix
+	if ! echo "$NEWNAME" | grep -q "^$HOTFIX_PREFIX" ; then
+		NEWNAME="$HOTFIX_PREFIX$NEWNAME"
+	fi
+
+	# we need to know the current state of $ORIGIN
+	hubflow_fetch_latest_changes_from_origin
+
+	# sanity checks
+	require_branch "$HOTFIX_BRANCH"
+	require_branch_absent "$NEWNAME"
+	require_branch_absent "$ORIGIN/$NEWNAME"
+	require_tag_absent "${NEWNAME#$HOTFIX_PREFIX}"
+
+	# keep track of what we did
+	local removed_remote=0
+
+	# do it
+	git branch -m "$HOTFIX_BRANCH" "$NEWNAME" || die "could not rename local branch"
+	if git_branch_exists "$ORIGIN/$HOTFIX_BRANCH" ; then
+		git push $ORIGIN ":$HOTFIX_BRANCH" || die "could not delete remote branch '$HOTFIX_BRANCH' at $ORIGIN"
+		removed_remote=1
+	fi
+	git push "$ORIGIN" "$NEWNAME" || die "could not push new branch '$NEWNAME' to $ORIGIN"
+
+	# summary
+	echo
+	echo "Summary of actions:"
+	echo "- The local branch '$HOTFIX_BRANCH' has been renamed to '$NEWNAME'."
+	if [[ $removed_remote == 1 ]] ; then
+		echo "- The remote branch '$HOTFIX_BRANCH' at $ORIGIN was removed."
+	fi
+	echo "- The local branch '$NEWNAME' has been pushed to $ORIGIN."
+	echo
 }
diff --git a/git-hf-release b/git-hf-release
--- a/git-hf-release
+++ b/git-hf-release
@@ -51,8 +51,9 @@ usage() {
 	echo "       git hf release start <version> [<base>]"
 	echo "       git hf release finish [-sumpk] <version>"
 	echo "       git hf release cancel <version>"
-	echo "       git hf release push [<name>]"
-	echo "       git hf release pull [<name>]"
+	echo "       git hf release push [<version>]"
+	echo "       git hf release pull [<version>]"
+	echo "       git hf release rename <new-version>"
 }
 
 cmd_default() {
@@ -133,6 +134,14 @@ parse_args() {
 require_version_arg() {
 	if [ "$VERSION" = "" ]; then
 		warn "Missing argument <version>"
+		usage
+		exit 1
+	fi
+}
+
+require_newversion_arg() {
+	if [[ -z $VERSION ]] ; then
+		warn "Missing argument <new-version>"
 		usage
 		exit 1
 	fi
@@ -532,4 +541,47 @@ use_current_release_branch_name() {
 		warn "Please specify a <name> argument."
 		exit 1
 	fi
+}
+
+cmd_rename() {
+	# sort out our args
+	parse_args "$@"
+	require_newversion_arg
+	NEWNAME=$VERSION
+	use_current_release_branch_name
+
+	# make sure the new branch has the release prefix
+	if ! echo "$NEWNAME" | grep -q "^$HOTFIX_PREFIX" ; then
+		NEWNAME="$RELEASE_PREFIX$NEWNAME"
+	fi
+
+	# we need to know the current state of $ORIGIN
+	hubflow_fetch_latest_changes_from_origin
+
+	# sanity checks
+	require_branch "$RELEASE_BRANCH"
+	require_branch_absent "$NEWNAME"
+	require_branch_absent "$ORIGIN/$NEWNAME"
+	require_tag_absent "${NEWNAME#$RELEASE_PREFIX}"
+
+	# keep track of what we did
+	local removed_remote=0
+
+	# do it
+	git branch -m "$RELEASE_BRANCH" "$NEWNAME" || die "could not rename local branch"
+	if git_branch_exists "$ORIGIN/$RELEASE_BRANCH" ; then
+		git push $ORIGIN ":$RELEASE_BRANCH" || die "could not delete remote branch '$RELEASE_BRANCH' at $ORIGIN"
+		removed_remote=1
+	fi
+	git push "$ORIGIN" "$NEWNAME" || die "could not push new branch '$NEWNAME' to $ORIGIN"
+
+	# summary
+	echo
+	echo "Summary of actions:"
+	echo "- The local branch '$RELEASE_BRANCH' has been renamed to '$NEWNAME'."
+	if [[ $removed_remote == 1 ]] ; then
+		echo "- The remote branch '$RELEASE_BRANCH' at $ORIGIN was removed."
+	fi
+	echo "- The local branch '$NEWNAME' has been pushed to $ORIGIN."
+	echo
 }
