Added git hf upgrade command

diff --git a/git-hf-upgrade b/git-hf-upgrade
--- a/git-hf-upgrade
+++ b/git-hf-upgrade
@@ -42,18 +42,45 @@
 #
 
 usage() {
-	echo "usage: git hf version"
+	echo "usage: git hf upgrade"
 }
 
 cmd_default() {
-	if hubflow_has_new_version_available > /dev/null ; then
-		echo "$HUBFLOW_VERSION - upgrade available"
-	else
-		echo "$HUBFLOW_VERSION - latest version"
-	fi
+	cmd_upgrade "$@"
 }
 
 cmd_help() {
 	usage
 	exit 0
+}
+
+cmd_upgrade() {
+	DEFINE_boolean check false "check for upgrade, but do not upgrade" c
+	# is there a new version available?
+	if ! hubflow_has_new_version_available > /dev/null ; then
+		die "You are already running the latest version"
+	elif flag check ; then
+		die "A newer version of the HubFlow tools is available"
+	fi
+
+	# make sure we have permissions
+	if [ `id -u` != 0 ] ; then
+		die "Not running as root (try using sudo?)"
+	fi
+
+	# make sure there isn't already a gitflow folder here
+	if [ -e gitflow ] ; then
+		die "Cannot clone the HubFlow repo; there's already a folder called 'gitflow' in your current working directory"
+	fi
+
+	git clone --recursive $HUBFLOW_REPO || die "Unable to clone the HubFlow repo"
+	cd gitflow || die "Could not find the gitflow repo we've just cloned"
+	./install.sh || die "Failed to install gitflow"
+	cd ..
+	rm -rf ./gitflow || die "Unable to remove the gitflow repo we've just cloned"
+
+	echo
+	echo "Summary of actions:"
+	echo "- A new version of the HubFlow tools has been installed"
+	echo
 }
