Fix: treat all support branches like the develop branch when updating / auto-merging

diff --git a/hubflow-common b/hubflow-common
--- a/hubflow-common
+++ b/hubflow-common
@@ -455,6 +455,20 @@ hubflow_merge_latest_changes_from_origin() {
         fi
     fi
 
+	# merge any support branches that exist
+	local support_branches=$(git_list_branches_of_type support)
+	for support_branch in $support_branches ; do
+		support_branch=$SUPPORT_PREFIX$support_branch
+		# skip support branches we don't use locally
+		if git_local_branch_exists $support_branch ; then
+			hubflow_remote_merge_helper "$ORIGIN" "$support_branch" no_checkout_afterwards
+			git_compare_branches "$support_branch" "$ORIGIN/$support_branch"
+			if [[ $? -ne 0 ]] ; then
+				git push "$ORIGIN" "$support_branch" || die "Push to '$ORIGIN' failed"
+			fi
+		fi
+	done
+
     # switch back to the original branch
     hubflow_branch_pop
 }
